name: publish

on:
  push:

permissions:
  contents: read
  packages: write

jobs:
  publish-otp-usermanagement-api-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: BiG-ADLER
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/big-adler/otp-usermanagement-api:latest .

      - name: Run container in background
        run: |
          docker run -d --name otp-usermanagement-api-test -p 3000:3000 ghcr.io/big-adler/otp-usermanagement-api:latest
          sleep 5
          curl -f http://localhost:3000/api/v1/status || (docker logs otp-test && false)
          docker stop otp-usermanagement-api-test

      - name: Push Docker image
        run: |
          docker push ghcr.io/big-adler/otp-usermanagement-api:latest
