name: publish

on: [push]

jobs:

publish-otp-usermanagement-api-image:

runs-on: ubuntu-latest

steps:

- uses: actions/checkout@v2

- name: Login to GitHub Container Registry

uses: docker/login-action@v1

with:

registry: ghcr.io

username: ${{ github.actor }}

password: ${{ secrets.GITHUB_TOKEN }}

- name: Build the otp-usermanagement-api Docker image

run: |

       docker build . --tag ghcr.io/BiG-ADLER/otp-usermanagement-api:latest

       docker run ghcr.io/BiG-ADLER/otp-usermanagement-api:latest

       docker push ghcr.io/BiG-ADLER/otp-usermanagement-api:latest