name: publish

on:
  push:

jobs:
  publish-otp-usermanagement-api-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/big-adler/otp-usermanagement-api:latest .

      - name: Run the image (for test only)
        run: |
          docker run --rm ghcr.io/big-adler/otp-usermanagement-api:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/big-adler/otp-usermanagement-api:latest
